theme: jekyll-theme-architect
description: "Practical ML for Low Resource Settings Workshop @ ICLR 2024, 
    <br/> Learning under limited/low resource scenarios"
basepath: "iclr2024/"
google_analytics: UA-156425047-1

navigation:
- text: HOME
  url: /
- text: CALL FOR PAPERS
  url: /cfp.html
- text: DATES
  url: /dates.html
  layout: project
#- text: PROGRAM
#  url: /program.html
#- text: PAPERS
#  url: /papers.html
- text: ORGANIZERS
  url: /organizers.html

